// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateArrival(ctx context.Context, arg CreateArrivalParams) (sql.Result, error)
	CreateGuest(ctx context.Context, arg CreateGuestParams) (sql.Result, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (sql.Result, error)
	DeleteGuest(ctx context.Context, id int32) error
	DeleteTable(ctx context.Context, id int32) error
	GetArrival(ctx context.Context, id int32) (Arrival, error)
	GetArrivalFromGuest(ctx context.Context, guestID int32) (Arrival, error)
	GetArrivals(ctx context.Context, arg GetArrivalsParams) ([]Arrival, error)
	GetArrivedGuests(ctx context.Context, arg GetArrivedGuestsParams) ([]Guest, error)
	GetEmptySeats(ctx context.Context) (int32, error)
	GetGuest(ctx context.Context, id int32) (Guest, error)
	GetGuestForUpdate(ctx context.Context, id int32) (Guest, error)
	GetGuestFromName(ctx context.Context, guestName string) (Guest, error)
	GetGuests(ctx context.Context, arg GetGuestsParams) ([]Guest, error)
	GetTable(ctx context.Context, id int32) (Table, error)
	GetTableForUpdate(ctx context.Context, id int32) (Table, error)
	GetTables(ctx context.Context, arg GetTablesParams) ([]Table, error)
	UpdateGuestArrival(ctx context.Context, arg UpdateGuestArrivalParams) error
	UpdateTable(ctx context.Context, arg UpdateTableParams) error
}

var _ Querier = (*Queries)(nil)
